kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven:3-jdk-10
  commands:
  - mvn clean install

trigger:
  ref:
  - refs/heads/master
  - refs/heads/**
  - refs/pull/*/head
